"""no circular fk

Revision ID: 353ee0154886
Revises: 
Create Date: 2025-09-22 20:52:13.226032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '353ee0154886'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('invite_code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_code'),
    schema='inspection_app'
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['inspection_app.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='inspection_app'
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['inspection_app.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inspection_app'
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['inspection_app.user.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['inspection_app.organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inspection_app'
    )
    op.create_table('inspection_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['inspection_app.user.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['inspection_app.templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inspection_app'
    )
    op.create_table('template_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('question', sa.String(length=255), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['inspection_app.templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inspection_app'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_items', schema='inspection_app')
    op.drop_table('inspection_results', schema='inspection_app')
    op.drop_table('templates', schema='inspection_app')
    op.drop_table('vehicles', schema='inspection_app')
    op.drop_table('user', schema='inspection_app')
    op.drop_table('organizations', schema='inspection_app')
    # ### end Alembic commands ###
