"""hopefully making new org table

Revision ID: 9c92485323b7
Revises: e5ed4fc01bf2
Create Date: 2025-09-20 20:47:31.703666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c92485323b7'
down_revision = 'e5ed4fc01bf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['inspection_app.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inspection_app'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organizations', schema='inspection_app')
    # ### end Alembic commands ###
