"""added invite_code to organization

Revision ID: b544306e7f4f
Revises: 4002d3293942
Create Date: 2025-09-20 23:08:42.805925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b544306e7f4f'
down_revision = '4002d3293942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema='inspection_app') as batch_op:
        batch_op.add_column(sa.Column('invite_code', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['invite_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema='inspection_app') as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('invite_code')

    # ### end Alembic commands ###
