"""added org_id to user model

Revision ID: c82cbcbbe7b9
Revises: 9c92485323b7
Create Date: 2025-09-20 20:48:18.610405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82cbcbbe7b9'
down_revision = '9c92485323b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema='inspection_app') as batch_op:
        batch_op.add_column(sa.Column('org_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'organizations', ['org_id'], ['id'], referent_schema='inspection_app')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema='inspection_app') as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('org_id')

    # ### end Alembic commands ###
