"""edited template and template_items to set up a default template

Revision ID: c9d6e6e99741
Revises: b2fdad17e675
Create Date: 2025-09-19 18:42:35.047452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d6e6e99741'
down_revision = 'b2fdad17e675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.String(length=255), nullable=False))
        batch_op.drop_column('description')

    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    with op.batch_alter_table('template_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('question')

    # ### end Alembic commands ###
